<h2>search songs </h2>
<?php echo $this->tag->form("search"); ?>
<p>
    <label for="name">song Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>
<p>

    <input type="checkbox" id="album" name="album" value="album">
    <label for="track">album </label> <br>
    <input type="checkbox" id="artist" name="artist" value="artist">
    <label for="artist">artist </label>
    <input type="checkbox" id="playlist" name="playlist" value="playlist">
    <label for="album">playlist </label>


</p>

<?php echo $this->tag->submitButton(
    [
        'search', 'name' => 'search', 'class' => 'btn btn-primary'
    ]
); ?>
</form>


<?php echo $this->tag->linkTo(
    [
        'search/createplaylist', 'create playlist', 'class' => 'btn btn-success m-2'
    ]
); ?>
<?php echo $this->tag->form("search/myplaylist"); ?>

<?php echo $this->tag->submitButton(
    [
        'myplaylist', 'name' => 'myplaylist', 'class' => 'btn btn-warning m-2'
    ]
); ?>
</form>
<?php echo $this->tag->linkTo(
    [
        '/dashboard', 'dashboard', 'class' => 'btn btn-danger m-2'
    ]
);    echo "<a href='/?val=1' class = 'btn btn-primary m-5'>signout</a>" ;?>
<?php
if (isset($album)) {
    $size = count($album);
  
    $html = '';
    if ($size > 0) {
        for ($i = 0; $i < $size; $i++) {
            $html .= '<div class = "row  container alert alert-success"><div class = "col-sm-6">
             <p> <strong>name: </strong>' . $album[$i]->name . '</p>
             <p> <strong>type: </strong>' . $album[$i]->type . '</p>
             <p><strong>total track: </strong>' . $album[$i]->total_tracks . '</p>
             </div><div class = "col-sm-6" ><img src = "' . $album[$i]->images[0]->url . '" width = "200px"  height = "150px"></div></div>';
        }
        echo $html;
    }
}
if (isset($artist)) {
    $size = count($artist);
    $html = '';
    if ($size > 0) {
        for ($i = 0; $i < $size; $i++) {
            $html .= '<div class = "row  container alert alert-success"><div class = "col-sm-6">
             <p> <strong>type: </strong>' . $artist[$i]->type . '</p>
             <p> <strong>name: </strong>' . $artist[$i]->name . '</p>
             <p> <strong>genres: </strong>' . $artist[$i]->generes[0] . '  ' . $artist[$i]->generes[1] . '</p>
             <p><strong>popularity: </strong>' . $artist[$i]->popularity . '</p>
             </div><div class = "col-sm-6" ><img src = "' . $artist[$i]->images[0]->url . '" width = "200px"  height = "150px"></div></div>';
        }
        echo $html;
    }
}
if (isset($playlist)) {
    $size = count($playlist);
    $html = '';
    if ($size > 0) {
        for ($i = 0; $i < $size; $i++) {
            $html .= '<div class = "row  container alert alert-success"><div class = "col-sm-6">
             <p> <strong>type: </strong>' . $playlist[$i]->type . '</p>
             <p> <strong>name: </strong>' . $playlist[$i]->name . '</p>
             <p> <strong>desc: </strong>' . $playlist[$i]->description . '</p>
             <p><strong>total tracks: </strong>' . $playlist[$i]->tracks->total . '</p>
             </div><div class = "col-sm-6" ><img src = "' . $playlist[$i]->images[0]->url . '" width = "200px"  height = "150px"></div></div>';
        }
        echo $html;
    }
}
if (isset($records)) {
    $size = count($records);
    $html = '';
    if ($size > 0) {
        for ($i = 0; $i < $size; $i++) {
            $html .= '<div class = "row  container alert alert-success"><div class = "col-sm-6">
         <p> <strong>type: </strong>' . $records[$i]->album->album_type . '</p>
         <p><strong>song: </strong>' . $records[$i]->album->name . '</p>
         <p><strong>artists: </strong>' . $records[$i]->album->artists[0]->name . '</p>
         <a href = "search/createplaylist?urls='.$records[$i]->uri.'" class = "btn btn-danger m-2">add to playlist</a>
         </div><div class = "col-sm-6" ><img src = "' . $records[$i]->album->images[0]->url . '" width = "200px"  height = "150px"></div></div>';
        }
        echo $html;
    }
}
